const $=s=>document.querySelector(s);let csrf="",jobId="",preview=null,refs=[];
async function api(path,options={}){options.headers={"Accept":"application/json",...(options.headers||{})};if(options.method&&options.method!=="GET")options.headers["X-CSRF-Token"]=csrf;if(options.body&&typeof options.body!=="string"){options.headers["Content-Type"]="application/json";options.body=JSON.stringify(options.body)}const r=await fetch(path,options);const data=await r.json();if(!r.ok||!data.ok)throw new Error(data.error||`HTTP ${r.status}`);return data}
function msg(value,error=false){const node=$("#message");node.textContent=value||"";node.classList.toggle("error",error)}
async function loadSession(){csrf=(await api("/api/session")).csrf}
$("#logout-form").addEventListener("submit",async e=>{e.preventDefault();try{await api("/logout",{method:"POST",body:{}});location.replace("/login")}catch(err){msg(err.message,true)}});
async function loadJobs(select){const data=await api("/api/jobs");const box=$("#jobs"),old=select||jobId;box.replaceChildren();for(const job of data.jobs){const option=document.createElement("option");option.value=job.id;option.textContent=`${job.label} — ${job.completed}/${job.total}`;box.append(option)}jobId=[...box.options].some(o=>o.value===old)?old:(box.value||"");box.value=jobId;if(jobId)await refreshAll();else clearView()}
function clearView(){for(const id of ["total","completed","queued","run-state"])$("#"+id).textContent="—";$("#markers").replaceChildren();$("#details").textContent="Создайте проект."}
async function refreshAll(){if(!jobId)return;const requestedJob=jobId;const [job,markers]=await Promise.all([api(`/api/jobs/${jobId}`),api(`/api/jobs/${jobId}/markers?q=${encodeURIComponent($("#search").value)}&status=${encodeURIComponent($("#status-filter").value)}`)]);if(requestedJob!==jobId)return;const s=job.state,run=s.codex_run||{};$("#total").textContent=s.inventory_total;$("#completed").textContent=`${s.completed}/${s.total}`;$("#queued").textContent=(s.priority_marker_ids||[]).length;$("#run-state").textContent=run.active?(run.phase_detail||"Работает"):(run.reason||run.status||"Не запущен");renderMarkers(markers.markers,markers.total);renderUsageLimit(s);$("#start").disabled=!!run.active;$("#stop").disabled=!run.active}
function renderUsageLimit(state){const input=$("#usage-limit");if(input.dataset.job!==jobId){input.dataset.job=jobId;input.dataset.dirty=""}if(!input.dataset.dirty)input.value=state.codex_min_remaining_percent||0;$("#usage-limit-status").textContent=state.usage_guard_text||""}
$("#usage-limit").addEventListener("input",e=>{e.target.dataset.dirty="1"});
$("#save-usage-limit").addEventListener("click",async()=>{try{if(!jobId)throw new Error("Выберите проект.");const input=$("#usage-limit"),threshold=Number(input.value),selectedJob=jobId;if(!input.value.trim()||!Number.isInteger(threshold)||threshold<0||threshold>99)throw new Error("Введите целое число от 0 до 99%.");await api(`/api/jobs/${selectedJob}/usage-limit`,{method:"POST",body:{codex_min_remaining_percent:threshold}});if(jobId===selectedJob){input.dataset.dirty="";await refreshAll();msg("Порог сохранён. Применяется со следующей проверки; старый процесс нужно перезапустить. Анализ не запущен.")}}catch(e){msg(e.message,true)}});
function renderMarkers(rows,total){const body=$("#markers");body.replaceChildren();for(const row of rows){const tr=document.createElement("tr");tr.dataset.id=row.id;const check=document.createElement("input");check.type="checkbox";check.dataset.marker=row.id;const td0=document.createElement("td");td0.append(check);const values=[row.status,row.warnClass,row.file,row.line];tr.append(td0,...values.map(v=>{const td=document.createElement("td");td.textContent=v??"";return td}));tr.addEventListener("click",e=>{if(e.target!==check)showMarker(row.id);for(const item of body.children)item.classList.toggle("selected",item===tr)});body.append(tr)}$("#shown").textContent=`Показано: ${rows.length} из ${total}`}
function checked(){return [...document.querySelectorAll("input[data-marker]:checked")].map(n=>n.dataset.marker)}
async function showMarker(id){try{const data=await api(`/api/jobs/${jobId}/markers/${encodeURIComponent(id)}`);$("#details").textContent=JSON.stringify({marker:data.marker,decision:data.decision},null,2)}catch(e){msg(e.message,true)}}
async function mutate(path,body,message){try{msg("Выполняю…");const data=await api(path,{method:"POST",body});msg([message,data.run?.resume_notice].filter(Boolean).join(" "));await refreshAll()}catch(e){msg(e.message,true)}}
$("#jobs").addEventListener("change",async e=>{jobId=e.target.value;await refreshAll()});$("#reload-jobs").addEventListener("click",()=>loadJobs(jobId));$("#refresh-markers").addEventListener("click",()=>mutate(`/api/jobs/${jobId}/refresh`,{},"Маркеры обновлены."));$("#start").addEventListener("click",()=>mutate(`/api/jobs/${jobId}/start`,{},"Анализ запущен."));$("#stop").addEventListener("click",()=>mutate(`/api/jobs/${jobId}/stop`,{},"Остановка запрошена."));$("#enqueue").addEventListener("click",()=>mutate(`/api/jobs/${jobId}/queue`,{ids:checked()},"Маркеры добавлены в очередь."));$("#dequeue").addEventListener("click",()=>mutate(`/api/jobs/${jobId}/dequeue`,{ids:checked()},"Маркеры убраны из очереди."));
let timer;function delayedRefresh(){clearTimeout(timer);timer=setTimeout(()=>refreshAll().catch(e=>msg(e.message,true)),250)}$("#search").addEventListener("input",delayedRefresh);$("#status-filter").addEventListener("change",delayedRefresh);
$("#new-project").addEventListener("click",()=>$("#project-dialog").showModal());$("#load-refs").addEventListener("click",async()=>{try{$("#refs-status").textContent="Загружаю…";refs=(await api("/api/repositories/refs",{method:"POST",body:{repository_url:$("#repository-url").value}})).refs;const box=$("#refs");box.replaceChildren();for(const [i,row] of refs.entries()){const o=document.createElement("option");o.value=String(i);o.textContent=`${row.kind}: ${row.name} · ${row.commit.slice(0,12)}`;box.append(o)}$("#refs-status").textContent=`Найдено: ${refs.length}`}catch(e){$("#refs-status").textContent=e.message}});$("#project-form").addEventListener("submit",async e=>{e.preventDefault();try{const selection=refs[Number($("#refs").value)];if(!selection)throw new Error("Выберите версию исходников.");msg("Создаю проект и получаю маркеры…");const data=await api("/api/jobs",{method:"POST",body:{snapshot_url:$("#snapshot-url").value,repository_url:$("#repository-url").value,selection}});$("#project-dialog").close();jobId=data.job_id;await loadJobs(jobId);msg(data.warning?`Проект создан, но маркеры не загружены: ${data.warning}`:"Проект и маркеры готовы.",!!data.warning)}catch(err){msg(err.message,true)}});
$("#preview-import").addEventListener("click",async()=>{try{const data=await api(`/api/jobs/${jobId}/import/preview`,{method:"POST",body:{}});preview=data.preview;const force=!!preview.requires_force,phrase=preview[force?"force_confirmation":"confirmation"]||"";$("#import-summary").textContent=`Маркеров: ${preview.marker_count}; конфликтов: ${preview.conflict_count}. ${force?"Существующая разметка будет заменена.":""}`;$("#confirmation-phrase").textContent=phrase;$("#confirmation").value="";$("#apply-import").disabled=false;$("#import-dialog").showModal()}catch(e){msg(e.message,true)}});$("#apply-import").addEventListener("click",()=>$("#import-dialog").showModal());$("#import-form").addEventListener("submit",async e=>{e.preventDefault();try{const data=await api(`/api/jobs/${jobId}/import/apply`,{method:"POST",body:{confirmation:$("#confirmation").value}});$("#import-dialog").close();msg(data.result?.verification?.verified?"Разметка отправлена и подтверждена.":"Отправка выполнена, но обратная проверка не подтверждена.",!data.result?.verification?.verified);await refreshAll()}catch(err){msg(err.message,true)}});
loadSession().then(()=>loadJobs()).then(()=>setInterval(()=>jobId&&refreshAll().catch(()=>{}),5000)).catch(e=>msg(e.message,true));
